# fly.toml app configuration file generated for api-lauraxv on 2024-10-02T19:13:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-lauraxv'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8083
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
